version: '3'
services:
  mysql:
    env_file: ./.env
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    networks:
      - app-network
  api:
    image: oricloud-app
    env_file: ./.env
    build: .
    ports:
      - '${PORT}:3001'
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mysql
networks:
  app-network:
    driver: bridge
